name: "Helm Action"
description: "Perform someting with Helm in the cluster"
inputs:
  kubeconfig:
    description: "The path to the kubeconfig file"
    required: true
    default: "./kubeconfig"
  chart:
    description: "The chart to install"
    required: true
    default: "helm-example"
  release:
    description: "The release name"
    required: true
    default: "helm-example"
  version:
    description: "The chart version"
    required: false
    default: ""
  namespace:
    description: "The namespace to install the chart"
    required: true
    default: "default"
  command: # id of input
    description: "Command for the Helm action"
    required: true
    default: "upgrade"
  values-file:
    description: "Values file for the Helm chart"
    required: false
    default: "null"
  values:
    description: "Values for the Helm chart"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.release }}
    - ${{ inputs.chart }}
    - --version
    - ${{ inputs.version }}
    - -n
    - ${{ inputs.namespace }}
    - --create-namespace
    - -f
    - ${{ inputs.values-file }}
    - --kubeconfig
    - ${{ inputs.kubeconfig }}
    - ${{ inputs.values }}
