name: "Uninstall Workflow"

on:
  workflow_dispatch:

jobs:
  runner-job:
    runs-on: self-hosted
    environment: local
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Configure kubeconfig"
        run: |
          cat <<EOF > ./kubeconfig
          ${{ secrets.KUBECONFIG }}
          EOF
      - name: "Uninstall a Valkey chart"
        uses: ./
        id: uninstall
        with:
          kubeconfig: "./kubeconfig"
          command: "uninstall"
          release: "valkey"
